automation/automation/urls.py
from django.conf.urls import url
from django.contrib import admin
from web import views

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    # 登陆 退出
    url(r'^login/', views.login, name='login'),
    url(r'^logout', views.logout, name='logout'),

    # 默认页面
    url(r'^index/', views.index, name='index'),

    # 用户
    url(r'^user/', views.user, name='user'),
    url(r'^useradd/', views.useradd, name='useradd'),
    url(r'^useredit/(\d+)', views.edit, name='useredit'),
    url(r'^userdel/(\d+)', views.userdel, name='userdel'),

    # 主机
    url(r'^host/', views.host, name='host'),
    url(r'^hostadd/', views.hostadd, name='hostadd'),
    url(r'^hostedit/(\d+)', views.hostedit, name='hostedit'),
    url(r'^hostdel/(\d+)', views.hostdel, name='hostdel'),

    # 初始化任务
    url(r'^init/', views.init, name='init'),
    url(r'^initadd/', views.initadd, name='initadd'),
    url(r'^initedit/(\d+)', views.initedit, name='initedit'),
    url(r'^initdel/(\d+)', views.initdel, name='initdel'),

    # 初始化主机
    url(r'^inithost/', views.inithost, name='inithost'),
    url(r'^initlog/(.*)', views.initlog, name='initlog'),

    # 项目
    url(r'^showproject/', views.project, name='showproject'),
    url(r'^projectadd/', views.projectadd, name='projectadd'),
    url(r'^projectedit/(\d+)', views.projectedit, name='projectedit'),
    url(r'^projectdel/(\d+)', views.projectdel, name='projectdel'),
    url(r'^projectinfo/(.*)', views.projectinfo, name='projectinfo'),

    # 命令下发
    url(r'^showissuance/', views.showissuance, name='showissuance'),
    url(r'^codeissuance/', views.codeissuance, name='codeissuance'),

    # 定时任务
    url(r'^showcron/', views.showcron, name='showcron'),
    url(r'^cronadd/',views.cronadd,name='cronadd'),
    url(r'^cronedit/(\d+)',views.cronedit,name='cronedit'),

    # 发布
    url(r'^showpublish/',views.showpublish,name='showpublish'),
    # 文件上传
    url(r'^createfile/',views.createfile,name='createfile'),
    # git添加
    url(r'^creategit/',views.creategit,name='creategit'),
    # TODO 发布的ansible动作未完成，showpublish的js动作未完成
]

automation/web/models.py
from django.db import models
from django.contrib.auth.models import User, Group
from django.contrib.auth.models import AbstractUser

# Create your models here.
status = (
    ("0", "等待更新"),
    ("1", "更新中"),
    ("2", "等待测试"),
    ("3", "测试通过"),
    ("4", "更新完成"),
    ("5", "更新失败"),
    ("6", "回滚成功"),
    ("7", "回滚失败")
)


class Project(models.Model):
    """
    项目表
    """
    Language = (
        ("0", 'python'),
        ("1", "java"),
        ("2", 'go'),
        ("3", "php"),
        ("4", "html")
    )
    name = models.CharField(verbose_name='项目名', max_length=200, unique=True)
    boss = models.ManyToManyField('UserProfile', verbose_name='责任人',related_name='boss')
    dev_user = models.ManyToManyField('UserProfile', verbose_name="研发人员",related_name="dev_user")
    test_user = models.ManyToManyField('UserProfile', verbose_name="测试人员",related_name="test_user")
    ops_user = models.ManyToManyField('UserProfile', verbose_name="运维人员",related_name="ops_user")
    path = models.CharField(verbose_name='项目目录', max_length=200)
    git_path = models.CharField(verbose_name='git地址', max_length=200)
    nginx_host = models.ManyToManyField('Host', verbose_name='nginx机器',related_name="nginx_host")
    nginx_conf = models.CharField(verbose_name='nginx配置文件', max_length=200, null=True, blank=True)
    server_host = models.ManyToManyField('Host', verbose_name='后端主机',related_name="server_host")
    language = models.CharField(verbose_name='语言', choices=Language, default="0", max_length=20)
    domain = models.CharField(verbose_name='域名', null=True, blank=True, max_length=100)
    note = models.CharField(verbose_name='备注信息', max_length=218, null=True, blank=True)
    create_time = models.DateTimeField("创建时间", auto_now_add=True)
    status = models.CharField(verbose_name="状态", choices=(("0", "可用"), ("1", "下线")), default="0", max_length=2)

    class Meta:
        ordering = ("-create_time",)

    def __str__(self):
        return self.name


class Host(models.Model):
    env = (
        ("0", '开发'),
        ("1", "测试"),
        ("2", "预生产"),
        ("3", "生产")
    )
    Type = (
        ("0", "nginx"),
        ("1", "redis"),
        ("2", "db"),
        ("3", "server"),

    )
    status = (
        ("0", "在线"),
        ("1", "下线"),
        ("2", "维修"),
    )
    name = models.CharField(verbose_name="主机名", max_length=200, unique=True)
    hostip = models.GenericIPAddressField(verbose_name='主机ip地址')
    env = models.CharField(verbose_name='环境', choices=env, default="3", max_length=20)
    version = models.CharField(verbose_name="系统版本", max_length=50, null=True, blank=True)
    type = models.CharField(verbose_name="类型", choices=Type, default="3", max_length=20)
    user=models.CharField(verbose_name="登录用户", max_length=50, null=True, blank=True,default="root")
    ssh_port = models.CharField(verbose_name="ssh端口", default=22, max_length=10)
    status = models.CharField(verbose_name="状态", choices=status, default="0", max_length=2)

    def __str__(self):
        return self.hostip


class Issue(models.Model):
    """
    # 更新表
    """
    project = models.ForeignKey(Project, verbose_name='发布项目')
    user = models.ForeignKey("UserProfile", verbose_name='发布人')
    create_time = models.DateTimeField("创建时间", auto_now_add=True)
    type = models.CharField(verbose_name='更新类型', choices=(("0", "文件"), ("1", "git")), default="0", max_length=20, )
    status = models.CharField(verbose_name='更新状态', choices=status, default="0", max_length=20)
    version = models.CharField(verbose_name="版本", null=True, blank=True, max_length=100)
    backup = models.CharField(verbose_name='备份状态', choices=(("0", "是"), ("1", "否")), default="0", max_length=20)
    backup_path = models.CharField(verbose_name='备份文件路径', max_length=2048, null=True, blank=True)
    upload_path = models.CharField(verbose_name='上传文件路径', max_length=2048, null=True, blank=True)

    class Meta:
        ordering = ['-create_time']


class Host_Issue(models.Model):
    """
    # 主机的更新信息表
    """
    host = models.ForeignKey(Host, verbose_name='发布机器')
    issue = models.ForeignKey(Issue, verbose_name='更新')
    status = models.CharField(verbose_name='更新状态', choices=status, default="0", max_length=20)
    update_time= models.DateTimeField("更新时间",auto_now=True)



class Command(models.Model):
    """
    命令表
    """
    command = models.CharField(verbose_name="命令", max_length=200)
    result = models.CharField(verbose_name="结果", max_length=2000)
    hosts_list = models.CharField(verbose_name="执行机器", max_length=20000)
    user = models.ForeignKey('UserProfile', verbose_name='用户')
    create_time = models.DateTimeField("创建时间", auto_now_add=True)

    class Meta:
        ordering = ['-create_time']


class UserProfile(models.Model):
    """
    用户表
    """
    name = models.CharField(verbose_name="用户名称", unique=True,max_length=200)
    email = models.CharField(verbose_name="邮箱地址", max_length=200)
    password = models.CharField(verbose_name="密码", max_length=200)
    role = models.CharField(verbose_name='角色', choices=(("0", "开发"), ("1", "测试"), ("2", '运维')), default="0",max_length=10)
    is_admin = models.CharField(verbose_name='管理员', choices=(("0", "Admin"), ("1", "普通")), default="1",max_length=10)
    is_unable = models.CharField(verbose_name='是否可用', choices=(("0", "可用"), ("1", "不可用")), default="0",max_length=10)
    department = models.CharField(verbose_name='部门',choices=(("0", "开发"), ("1", "测试"), ("2", '运维')), blank=True, null=True, max_length=10)
    phone = models.CharField(verbose_name='手机号', blank=True, null=True, max_length=11)
    create_time = models.DateTimeField("创建时间", auto_now_add=True)

    class Meta:
        ordering = ['-create_time']

    def __str__(self):
        return self.name


class Cron(models.Model):
    """
    计划任务
    """
    name = models.CharField(verbose_name="计划名称", unique=True, max_length=64)
    hosts_list = models.ManyToManyField(Host, verbose_name="执行机器")
    user = models.CharField(verbose_name="执行用户", null=True, blank=True, default='root', max_length=256)
    job = models.CharField(verbose_name="计划", max_length=1024)
    time = models.CharField(verbose_name="计划任务执行的时间", max_length=64)
    create_time = models.DateTimeField("创建时间", auto_now_add=True)
    create_user = models.ForeignKey(UserProfile, verbose_name="创建者")
    note = models.CharField(verbose_name="计划描述", null=True, blank=True, max_length=256)

    class Meta:
        ordering = ['-create_time']

    def __str__(self):
        return self.name


class Init(models.Model):
    """
    初始化表
    """
    name = models.CharField(verbose_name="名称", unique=True, max_length=64)
    function = models.CharField(verbose_name="初始化功能", unique=True, max_length=64)
    play_book = models.CharField(verbose_name="playbook路径", max_length=100)
    create_time = models.DateTimeField("创建时间", auto_now_add=True)
    create_user = models.ForeignKey(UserProfile, verbose_name="创建者")

    class Meta:
        ordering = ('-create_time',)

    def __str__(self):
        return self.name


class InitLog(models.Model):
    """
    初始化日志表
    """
    init = models.ForeignKey(Init, verbose_name="初始化功能")
    hosts_list = models.ManyToManyField(Host, verbose_name="执行机器")
    user = models.ForeignKey(UserProfile, verbose_name="创建者")
    create_time = models.DateTimeField("创建时间", auto_now_add=True)
    result=models.CharField(verbose_name="结果",max_length=1000,null=True,blank=True)

    class Meta:
        ordering = ('-create_time',)

automation/templates/createfile.html
<form class="form-horizontal" id="createForm" action="" method="post" enctype="multipart/form-data">{% csrf_token %}
    <div class="box-body">
        {% for field in form_obj %}
            <div class="form-group{% if field.errors %} has-error{% endif %}">
                <label class="col-sm-2 control-label">{{ field.label }}
                    {% if field.field.required %}
                        <span class="text-red">*</span>
                    {% endif %}
                </label>
                <div class="col-sm-9">
                    {{ field }}
                </div>
                <span class="help-block">
                  {% for error in field.errors %}
                      {{ error }}
                  {% endfor %}
                 {{ field.help_text }}
                </span>
            </div>
        {% endfor %}
        <div class="box-footer text-center">
            <button type="reset" class="btn btn-warning">清空</button>
            <button id="createBtn" type="button" class="btn btn-info">提交</button>
            <p class="text-center"><i id='iconWait'></i></p>
        </div>
    </div>
</form>
{% block js %}
    <script>
    $("#createBtn").on("click",function () {
        var formdata= new FormData(document.getElementById("createForm"));
        Net.post({
            url:"{% url 'createfile' %}",
            contentType:false, //告诉浏览器不要对数据进行转换
            processData:false,
            data:formdata,
            go:"{% url 'showpublish' %}",
            btn:$("#createBtn")
        })
    })
    </script>
{% endblock %}

automation/templates/cron.html
{% extends 'master/base.html' %}
{% load static %}

{% block css %}
    <link rel="stylesheet" href="{% static 'zTree_v3/css/zTreeStyle/zTreeStyle.css' %}" type="text/css">
{% endblock %}

{% block body %}
    <div class="row">
        <div class="col-md-6">
            <div class="zTreeDemoBackground left">
                <form id="cronform" class="form-horizontal" novalidate>
                    {% csrf_token %}
                    {% for field in cron_obj %}
                        <div class="form-group">
                            <label class="col-sm-2 control-label"
                                   for="{{ field.id_for_label }}">{{ field.label }}</label>
                            <div class="col-sm-9">
                                {{ field }}
                            </div>
                            <span class="text-danger">{{ field.errors.0 }}</span>
                        </div>
                    {% endfor %}
                    <div class="text-center">
                        <a href="{% url 'showcron' %}" type="button" class="btn btn-primary">返回</a>
                        <button type="reset" class="btn btn-warning">清空</button>
                        <button id="push" type="button" class="btn btn-info">提交</button>
                        <p class="text-center"><i id='iconWait'></i></p>
                    </div>
                </form>
            </div>
        </div>
        <div class="col-md-6">
            <div class="bg-black-active color-palette" style="height: 470px; overflow: auto">
                <p> 任务名称:</p>
                <p id="cron_name"></p>
                <p> 任务:</p>
                <p id="cron_job"></p>
                <p> 任务时间:</p>
                <p id="cron_time"></p>
                <p> 备注:</p>
                <p id="cron_note"></p>
            </div>
        </div>
    </div>

{% endblock %}

{% block js %}
    <script>
        $('select').select2();

        $("#cron").addClass("active");

        $('#cronform').change(
            function schedule() {
                time = "" + $('#id_minute').val() + " " + $('#id_hour').val() + " " + $('#id_day').val() + " " + $('#id_month').val() + " " + $('#id_weekday').val();
                $("#cron_time").text(time);
                $("#cron_name").text($("#id_name").val());
                $("#cron_job").text($("#id_job").val());
                $("#cron_note").text($("#id_note").val());
            });
        var time = "" + $('#id_minute').val() + " " + $('#id_hour').val() + " " + $('#id_day').val() + " " + $('#id_month').val() + " " + $('#id_weekday').val();
        $("#cron_time").text(time);


        $('#push').click(function () {
            var url = "{% url 'cronadd' %}";
            Net.post({
                    url: url,
                    data: $('#cronform').serialize(),
                    go:{% url 'showcron' %}
                }
            )
        });
    </script>
{% endblock %}

automation/templates/cronedit.html
{% extends 'master/base.html' %}
{% load static %}

{% block css %}
    <link rel="stylesheet" href="{% static 'zTree_v3/css/zTreeStyle/zTreeStyle.css' %}" type="text/css">
{% endblock %}

{% block body %}
    <div class="row">
        <div class="col-md-6">
            <div class="zTreeDemoBackground left">
                <form id="cronform" class="form-horizontal" novalidate>
                    {% csrf_token %}
                    {% for field in form_obj %}
                        <div class="form-group">
                            <label class="col-sm-2 control-label"
                                   for="{{ field.id_for_label }}">{{ field.label }}</label>
                            <div class="col-sm-9">
                                {{ field }}
                            </div>
                            <span class="text-danger">{{ field.errors.0 }}</span>
                        </div>
                    {% endfor %}
                    <div class="text-center">
                        <a href="{% url 'showcron' %}" type="button" class="btn btn-primary">返回</a>
                        <button type="reset" class="btn btn-warning">清空</button>
                        <button id="push" type="button" class="btn btn-info">提交</button>
                        <p class="text-center"><i id='iconWait'></i></p>
                    </div>
                </form>
            </div>
        </div>
        <div class="col-md-6">
            <div class="bg-black-active color-palette" style="height: 470px; overflow: auto">
                <p> 任务名称:</p>
                <p id="cron_name"></p>
                <p> 任务:</p>
                <p id="cron_job"></p>
                <p> 任务时间:</p>
                <p id="cron_time"></p>
                <p> 备注:</p>
                <p id="cron_note"></p>
            </div>
        </div>
    </div>

{% endblock %}

{% block js %}
    <script>
        $('select').select2();

        $("#cron").addClass("active");

        $('#cronform').change(
            function schedule() {
                time = "" + $('#id_minute').val() + " " + $('#id_hour').val() + " " + $('#id_day').val() + " " + $('#id_month').val() + " " + $('#id_weekday').val();
                $("#cron_time").text(time);
                $("#cron_name").text($("#id_name").val());
                $("#cron_job").text($("#id_job").val());
                $("#cron_note").text($("#id_note").val());
            });
        $('#id_name').attr('readonly',true);

        $('#push').click(function () {
            var url = "{% url 'cronedit' pk %}";
            Net.post({
                    url: url,
                    data: $('#cronform').serialize(),
                    go:{% url 'showcron' %}
                }
            )
        });
    </script>
{% endblock %}

automation/templates/edit.html
<div class="container-fluid">
    <div class="row">
        <div class="col-md-10 col-md-offset-1">
            <form novalidate>
                {% csrf_token %}
                {% for field in form_obj %}
                    <div class="form-group">
                        <label for="{{ field.id_for_label }}">{{ field.label }}</label>
                        {{ field }}
                        <span class="text-danger">{{ field.errors.0 }}</span>
                    </div>
                {% endfor %}
                <p class="wait pull-right" style="margin-top: 10px"></p>
                <input type="button" class="btn btn-success pull-right push" value="提交">
            </form>
        </div>
    </div>
</div>

<script>
    $('.push').click(function () {
        var name = $('#id_name').val();
        var email = $('#id_email').val();
        var password = $('#id_password').val();
        var role = $('#id_role').val();
        var is_admin = $('#id_is_admin').val();
        var is_unable = $('#id_is_unable').val();
        var department = $('#id_department').val();
        var phone = $('#id_phone').val();
        var csrf_token = $('[name=csrfmiddlewaretoken]').val();
        var url = "{% url 'useredit' pk %}";
        Net.post({
            'data':
                {
                    'name': name,
                    'email': email,
                    'password': password,
                    'role': role,
                    'is_admin': is_admin,
                    'is_unable': is_unable,
                    'department': department,
                    'phone': phone,
                    csrfmiddlewaretoken: csrf_token,
                },
            'url': url,
            'btn': $('.push'),
            'icon': $('.wait'),
            'go': "{% url 'user' %}",
        })
    })
</script>

automation/templates/host.html
{% extends 'master/base.html' %}
{% block body %}
    <div class="row">
        <div class="col-xs-12">
            <div class="box">
                <div class="box-header">
                    <h3 class="box-title">
                        <div class="btn btn-sm btn-success btn-add">添加主机</div>
                    </h3>
                    <form action="" method="get" class="pull-right">
                        <div class="box-tools">
                            <div class="input-group input-group-sm hidden-xs" style="width: 150px;">
                                <input type="text" name="table_search" class="form-control pull-right"
                                       placeholder="Search">

                                <div class="input-group-btn">
                                    <button type="submit" class="btn btn-default"><i class="fa fa-search"></i></button>
                                </div>
                            </div>
                        </div>
                    </form>
                </div>
                <!-- /.box-header -->
                <div class="box-body table-responsive no-padding">
                    <table class="table table-hover">
                        <thead>
                        <tr>
                            <th>编号</th>
                            <th>主机名</th>
                            <th>ip地址</th>
                            <th>环境</th>
                            <th>系统版本</th>
                            <th>服务类型</th>
                            <th>登陆用户</th>
                            <th>ssh端口</th>
                            <th>状态</th>
                            <th>操作</th>
                        </tr>
                        </thead>
                        <tbody>
                        {% for foo in host_obj %}
                            <tr>
                                <td>{{ forloop.counter }}</td>
                                <td>{{ foo.name }}</td>
                                <td>{{ foo.hostip }}</td>
                                <td>{{ foo.get_env_display }}</td>
                                <td>{{ foo.version }}</td>
                                <td>{{ foo.get_type_display }}</td>
                                <td>{{ foo.user }}</td>
                                <td>{{ foo.ssh_port }}</td>
                                <td>{{ foo.get_status_display }}</td>
                                <td>
                                    <button data-url="{% url 'hostedit' foo.pk %}"
                                            class="btn btn-warning btn-sm btn-edit">编辑
                                    </button>
                                    <button data-url="{% url 'hostdel' foo.pk %}" class="btn btn-danger btn-sm btn-del">
                                        删除
                                    </button>
                                </td>
                            </tr>
                        {% endfor %}
                        </tbody>
                    </table>
                </div>
                <!-- /.box-body -->
            </div>
            <!-- /.box -->
        </div>
    </div>
{% endblock %}

{% block js %}
    <script>
        $("#host").addClass("active");
        $('.btn-add').click(function () {
            ui.box(
                {
                    'title': '添加主机',
                    'remote': "{% url 'hostadd' %}",
                }
            )
        });
        $('.btn-edit').click(function () {
            ui.box(
                {
                    'title': '编辑主机',
                    'remote': $(this).attr('data-url'),
                }
            )
        });
        $('.btn-del').click(function () {
            var url = $(this).attr('data-url'); <!-- 这里定义url是因为当使用了confirm后，this就变成了confirm，所以url在这里直接定义好-->
            ui.confirm('确认要删除吗?', function () {
                console.log($(this));
                Net.get({
                    url: url,
                    reload: true,
                })
            })
        })
    </script>
{% endblock %}

automation/templates/hostadd.html
<div class="container-fluid">
    <div class="row">
        <div class="col-md-10 col-md-offset-1">
            <form id="hostform" novalidate>
                {% csrf_token %}
                {% for field in host_obj %}
                    <div class="form-group">
                        <label for="{{ field.id_for_label }}">{{ field.label }}</label>
                        {{ field }}
                    </div>
                {% endfor %}
                <p class="wait pull-right" style="margin-top: 10px"></p>
                <input type="button" class="btn btn-success pull-right push" value="提交">
            </form>
        </div>
    </div>
</div>

<script>
    $('select').select2();
    $('.push').click(function () {
        var url = "{% url 'hostadd' %}";
        Net.post({
            url:url,
            data:$("#hostform").serialize(),
            go:"{% url 'host' %}"
        })
    })
</script>

automation/templates/project.html
{% extends 'master/base.html' %}
{% block body %}
    <div class="row">
        <div class="col-xs-12">
            <div class="box">
                <div class="box-header">
                    <h3 class="box-title">
                        <div class="btn btn-sm btn-success btn-add">添加项目</div>
                    </h3>
                    <form action="" method="get" class="pull-right">
                        <div class="box-tools">
                            <div class="input-group input-group-sm hidden-xs" style="width: 150px;">
                                <input type="text" name="table_search" class="form-control pull-right"
                                       placeholder="Search">

                                <div class="input-group-btn">
                                    <button type="submit" class="btn btn-default"><i class="fa fa-search"></i></button>
                                </div>
                            </div>
                        </div>
                    </form>
                </div>
                <!-- /.box-header -->
                <div class="box-body table-responsive no-padding">
                    <table class="table table-hover">
                        <thead>
                        <tr>
                            <th>编号</th>
                            <th>项目名</th>
                            <th>责任人</th>
                            <th>项目目录</th>
                            <th>git地址</th>
                            <th>域名</th>
                            <th>语言</th>
                            <th>状态</th>
                            <th>操作</th>
                        </tr>
                        </thead>
                        <tbody>
                        {% for foo in project_obj %}
                            <tr>
                                <td>{{ forloop.counter }}</td>
                                <td>{{ foo.name }}</td>
                                <td>{% for v in foo.boss.all %}
                                    {{ v.name }}
                                {% endfor %}
                                </td>
                                <td>{{ foo.path }}</td>
                                <td>{{ foo.git_path }}</td>
                                <td>{{ foo.domain }}</td>
                                <td>{{ foo.get_language_display }}</td>
                                <td>{{ foo.get_status_display }}</td>
                                <td>
                                    <button data-url="{% url 'projectedit' foo.pk %}"
                                            class="btn btn-warning btn-sm btn-edit">编辑
                                    </button>
                                    <button data-url="{% url 'projectdel' foo.pk %}"
                                            class="btn btn-danger btn-sm btn-del">删除
                                    </button>
                                    <button data-url="{% url 'projectinfo' foo.name %}"
                                            class="btn btn-success btn-sm btn-details">详情
                                    </button>
                                </td>
                            </tr>
                        {% endfor %}
                        </tbody>
                    </table>
                </div>
                <!-- /.box-body -->
            </div>
            <!-- /.box -->
        </div>
    </div>
{% endblock %}

{% block js %}
    <script>
        $("#project").addClass("active");
        $('.btn-add').click(function () {
            ui.box(
                {
                    'title': '添加项目',
                    'remote': "{% url 'projectadd' %}",
                }
            )
        });
        $('.btn-edit').click(function () {
            ui.box(
                {
                    'title': '编辑用户',
                    'remote': $(this).attr('data-url'),
                }
            )
        });
        $('.btn-del').click(function () {
            var url = $(this).attr('data-url');
            ui.confirm('确认要删除吗?', function () {
                Net.get({
                    url: url,
                    reload: true,
                })
            })
        });
        $('.btn-details').click(function () {
            var url = $(this).attr('data-url');
            ui.box({
                'title': '项目详情',
                'remote': url,
            })
        })
    </script>
{% endblock %}

automation/templates/showpublish.html
{% extends 'master/base.html' %}
{% block body %}

    <div class="row">
        <div class="col-xs-12">
            <div class="box">
                <div class="box-header">
                    <h3 class="box-title">
                        <div class="btn btn-sm btn-success git-btn">git更新</div>
                        <div class="btn btn-sm btn-success file-btn">文件更新</div>
                    </h3>
                    <form action="" method="get" class="pull-right">
                        <div class="box-tools">
                            <div class="input-group input-group-sm hidden-xs" style="width: 150px;">
                                <input type="text" name="table_search" class="form-control pull-right"
                                       placeholder="Search">

                                <div class="input-group-btn">
                                    <button type="submit" class="btn btn-default"><i class="fa fa-search"></i></button>
                                </div>
                            </div>
                        </div>
                    </form>
                </div>
                <!-- /.box-header -->
                <div class="box-body table-responsive no-padding">
                    <table class="table table-hover text-center">
                        <tr class="text-center">
                            <th>序号</th>
                            <th>项目名称</th>
                            <th>发布类型</th>
                            <th>发布人</th>
                            <th>发布状态</th>
                            <th>发布时间</th>
                            <th>操作</th>
                        </tr>
                        {% for foo in publish_obj %}
                            <tr>
                                <td>{{ forloop.counter }}</td>
                                <td>{{ foo.project.name }}</td>
                                <td>{{ foo.get_type_display }}</td>
                                <td>{{ foo.user.name }}</td>
                                <td>{{ foo.get_status_display }}</td>
                                <td>{{ foo.create_time|date:"Y-m-d h:i:s" }}</td>
                                <td>
                                    <div href="#" data-url="#" class="btn btn-sm btn-danger del-btn">开始更新</div>
                                    <div href="#" data-url="#" class="btn btn-sm btn-info detail-btn">详情</div>
                                </td>
                            </tr>
                        {% endfor %}

                    </table>
                </div>
                <!-- /.box-body -->
            </div>
            <div>
                <ul class="pagination pagination-sm no-margin pull-right">
                </ul>
                <!-- /.box -->
            </div>
            <!-- /.box -->
        </div>
    </div>

{% endblock %}


{% block js %}
    <script>
        $("#menu_issue").addClass("active");
        $("#issue").addClass("active");

        <!--文件上传-->
        $('.file-btn').click(function () {
            ui.box({
                title: '文件上传',
                remote: '{% url 'createfile' %}'
            })
        });

        <!--git更新-->
        $(".git-btn").on("click", function () {
            ui.box({
                "title": "git更新",
                "remote": "{% url 'creategit' %}"
            })
        })
    </script>
{% endblock %}