managerment_system/managerment_system/urls.py
from django.conf.urls import url
from django.contrib import admin
from app01 import views

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    # 注册
    url(r'^regiest/',views.regiest,name='regiest'),
    # 登录
    url(r'^login/',views.login,name='login'),
    # 验证码图片
    url(r'^code/',views.code,name='code'),
    # 默认页面
    url(r'^index/',views.index,name='index'),
    # 退出
    url(r'^logout',views.logout,name='logout'),
    # 展示所有客户信息
    url(r'^customers/list/', views.customers, name='customers'),
    # 添加
    url(r'^add$', views.add, name='add'),
    # 删除跟进记录
    url(r'delfollow/(\d+)',views.delfollow,name='delfollow'),
    # 删除
    url(r'^delete/(\d+)', views.delete, name='delete'),
    # 编辑跟进记录
    url(r'editfollow/(\d+)',views.editfollow,name='editfollow'),
    # 编辑
    url(r'^edit/(\d+)', views.edit, name='edit'),
    # 私户信息展示
    url(r'^mycustomers/', views.mycustomers, name='mycustomers'),
    # 跟进记录
    url(r'^followrecord/$',views.followrecord,name='followrecord'),
    # 公共页面的查看记录详情
    url(r'^followrecord/(\d+)',views.followrecord,name='singlerecord'),
    # 添加跟进记录
    url(r'^addfollow/',views.addfollow,name='addfollow'),
    # 展示班级信息
    url(r'^showclass/',views.showclass,name='showclass'),
]

managerment_system/app01/models.py
from django.db import models
# from django.contrib.auth.models import AbstractUser
from django.contrib.auth.models import AbstractUser,AbstractBaseUser,User,PermissionsMixin
from multiselectfield import MultiSelectField

# Create your models here.

course_choices = (('LinuxL', 'Linux中高级'),
                  ('PythonFullStack', 'Python高级全栈开发'),)

class_type_choices = (('fulltime', '脱产班',),
                      ('online', '网络班'),
                      ('weekend', '周末班',),)

source_type = (('qq', "qq群"),
               ('referral', "内部转介绍"),
               ('website', "官方网站"),
               ('baidu_ads', "百度推广"),
               ('office_direct', "直接上门"),
               ('WoM', "口碑"),
               ('public_class', "公开课"),
               ('website_luffy', "路飞官网"),
               ('others', "其它"),)

enroll_status_choices = (('signed', "已报名"),
                         ('unregistered', "未报名"),
                         ('studying', '学习中'),
                         ('paid_in_full', "学费已交齐"))

seek_status_choices = (('A', '近期无报名计划'), ('B', '1个月内报名'), ('C', '2周内报名'), ('D', '1周内报名'),
                       ('E', '定金'), ('F', '到班'), ('G', '全款'), ('H', '无效'),)
pay_type_choices = (('deposit', "订金/报名费"),
                    ('tuition', "学费"),
                    ('transfer', "转班"),
                    ('dropout', "退学"),
                    ('refund', "退款"),)

attendance_choices = (('checked', "已签到"),
                      ('vacate', "请假"),
                      ('late', "迟到"),
                      ('absence', "缺勤"),
                      ('leave_early', "早退"),)

score_choices = ((100, 'A+'),
                 (90, 'A'),
                 (85, 'B+'),
                 (80, 'B'),
                 (70, 'B-'),
                 (60, 'C+'),
                 (50, 'C'),
                 (40, 'C-'),
                 (0, ' D'),
                 (-1, 'N/A'),
                 (-100, 'COPY'),
                 (-1000, 'FAIL'),)

class UserInfo(AbstractUser):
    roles = models.ManyToManyField('Role')

    def __str__(self):
        return self.username

class Customer(models.Model):
    """
    客户表（最开始的时候大家都是客户，销售就不停的撩你，你还没交钱就是个客户）
    """
    qq = models.CharField(verbose_name='QQ', max_length=64, unique=True, help_text='QQ号必须唯一')
    qq_name = models.CharField('QQ昵称', max_length=64, blank=True, null=True)
    name = models.CharField('姓名', max_length=32, blank=True, null=True, help_text='学员报名后，请改为真实姓名')
    sex_type = (('male', '男'), ('female', '女'))
    sex = models.CharField("性别", choices=sex_type, max_length=16, default='male', blank=True, null=True) #存的是male或者female，字符串
    birthday = models.DateField('出生日期', default=None, help_text="格式yyyy-mm-dd", blank=True, null=True)

    phone = models.CharField('手机号', blank=True, null=True,max_length=32)
    # phone = models.CharField('手机号', blank=True, null=True)
    source = models.CharField('客户来源', max_length=64, choices=source_type, default='qq')

    introduce_from = models.ForeignKey('self', verbose_name="转介绍自学员", blank=True, null=True)  #self指的就是自己这个表，和下面写法是一样的效果


    # introduce_from = models.ForeignKey('Customer', verbose_name="转介绍自学员", blank=True, null=True,on_delete=models.CASCADE)
    course = MultiSelectField("咨询课程", choices=course_choices) #多选，并且存成一个列表的格式
    # course = models.CharField("咨询课程", choices=course_choices) #如果你不想用上面的多选功能，可以使用Charfield来存
    class_type = models.CharField("班级类型", max_length=64, choices=class_type_choices, default='fulltime')
    customer_note = models.TextField("客户备注", blank=True, null=True, )
    status = models.CharField("状态", choices=enroll_status_choices, max_length=64, default="unregistered",help_text="选择客户此时的状态") #help_text这种参数基本都是针对admin应用里面用的

    date = models.DateTimeField("咨询日期", auto_now_add=True)

    last_consult_date = models.DateField("最后跟进日期", auto_now_add=True) #考核销售的跟进情况，如果多天没有跟进，会影响销售的绩效等
    next_date = models.DateField("预计再次跟进时间", blank=True, null=True) #销售自己大概记录一下自己下一次会什么时候跟进，也没啥用

    #用户表中存放的是自己公司的所有员工。
    consultant = models.ForeignKey('UserInfo', verbose_name="销售", blank=True, null=True)

    def __str__(self):
        return self.name+":"+self.qq  #主要__str__最好是个字符串昂，不然你会遇到很多的坑，还有我们返回的这两个字段填写数据的时候必须写上数据，必然相加会报错，null类型和str类型不能相加等错误信息。

    # def get_classlist(self):  #当我们通过self.get_classlist的时候，就拿到了所有的班级信息，前端显示的时候用
    #
    #     l=[]
    #     for cls in self.class_list.all():
    #         l.append(str(cls))
    #     # return mark_safe(",".join(l)) #纯文本，不用mark_safe也可以昂
    #     return ",".join(l) #纯文本，不用mark_safe也可以昂

class Campuses(models.Model):
    """
    校区表
    """
    name = models.CharField(verbose_name='校区', max_length=64)
    address = models.CharField(verbose_name='详细地址', max_length=512, blank=True, null=True)

    def __str__(self):
        return self.name

class ConsultRecord(models.Model):
    customer = models.ForeignKey('Customer',verbose_name='所咨询的客户')
    note = models.TextField('跟进内容',null=True,blank=True)
    status = models.CharField('跟进状态',choices=seek_status_choices,max_length=8)
    consultant = models.ForeignKey('UserInfo',verbose_name='跟进人')
    date = models.DateTimeField('跟进日期')
    delete_status = models.BooleanField('删除状态',default=False)

class Role(models.Model):
    name = models.CharField(max_length=32)
    permissions = models.ManyToManyField('Permission')
    def __str__(self):
        return self.name

class Menu(models.Model):
    name = models.CharField(max_length=32,verbose_name='一级菜单')

class Permission(models.Model):
    name = models.CharField(max_length=32)
    url = models.CharField(max_length=128)
    menu = models.ForeignKey('Menu',null=True,blank=True)
    pid = models.ForeignKey('self',null=True)

    # is_menu = models.BooleanField(default=False,verbose_name='是否是菜单')

    def __str__(self):
        return self.name


class ClassList(models.Model):
    """
    班级表
    """
    course = models.CharField("课程名称", max_length=64, choices=course_choices)
    semester = models.IntegerField("学期") #python20期等
    campuses = models.ForeignKey('Campuses', verbose_name="校区",on_delete=models.CASCADE)
    price = models.IntegerField("学费", default=10000)
    memo = models.CharField('说明', blank=True, null=True, max_length=100)
    start_date = models.DateField("开班日期")
    graduate_date = models.DateField("结业日期", blank=True, null=True)

    teachers = models.ManyToManyField('UserInfo', verbose_name="老师")

    class_type = models.CharField(choices=class_type_choices, max_length=64, verbose_name='班额及类型', blank=True,null=True)

    def __str__(self):
        return "{}{}({})".format(self.get_course_display(), self.semester, self.campuses)

managerment_system/templates/add.html
{% extends 'base.html' %}

{% block content %}

    <h3>这是添加页面</h3>
    <div class="container-fluid">
        <div class="row">
            <div class="col-md-8 col-md-offset-2">
                <form action="{% url 'add' %}" method="post" novalidate>
                    {% csrf_token %}
                    {% for field in customer_obj %}
                        <div class="form-group">
                            <label for="{{ field.id_for_label }}">{{ field.label }}</label>
                            {{ field }}
                            <span class="text-danger">{{ field.errors.0 }}</span>
                        </div>
                    {% endfor %}

                    <input type="submit" class="btn btn-success pull-right" value="提交">
                </form>
            </div>
        </div>
    </div>

{% endblock %}

managerment_system/templates/addfollow.html
{% extends 'base.html' %}

{% block content %}
    <h3>添加跟进记录</h3>
    <div class="container-fluid">
        <div class="row">
            <div class="col-md-8 col-md-offset-2">
                <form action="" method="post" novalidate>
                    {% csrf_token %}
                    {% for follow in follow_obj %}
                        <div class="form-group">
                            <lebal for="{{ follow.id_for_label }}">{{ follow.label }}</lebal>
                            {{ follow }}
                            <span class="text-danger">{{ follow.errors.0 }}</span>
                        </div>
                    {% endfor %}
                    <input type="submit" value="提交" class="btn btn-success pull-right">
                </form>
            </div>
        </div>
    </div>
{% endblock %}

managerment_system/templates/customers.html
{% extends 'base.html' %}

{% block content %}
    <div style="margin-top: 10px;margin-left: 20px;">
{#        <li type="none"><a href="#">首页</a></li>#}
    {% for bread in request.menu_breadcrumb %}
        <li type="none"><a href="{{ bread.url }}">{{ bread.title }}</a></li>
    {% endfor %}
    
    </div>
    <section class="content">
        <div class="row">
            <div class="col-xs-12">
                <div class="box">
                    <div class="box-header">
                        <div>
                            <h3 class="box-title">客户信息展示</h3>
                        </div>
                        <div>
                            <br>
                            <form action="" method="get" class="pull-right" style="width: 400px;display: inline-block">
                                <select name="condition" id="" class="form-control"
                                        style="width: 100px;display: inline-block">
                                    <option value="name__contains">姓名</option>
                                    <option value="qq__contains">QQ</option>
                                </select>
                                <input type="text" name="wd" class="form-control"
                                       style="width: 200px;display: inline-block">
                                <button class="btn btn-default">搜索</button>
                            </form>
                            <a href="{% url 'add' %}" style="margin-left:10px;"
                               class="btn btn-primary pull-left">添加</a>
                            <form action="{% url 'customers' %}" method="post">
                                {% csrf_token %}
                                <select name="action" id="" class="form-control"
                                        style="width: 200px;display: inline-block;margin-left: 5px;">
                                    <option value="batch_delete">批量删除</option>
                                    <option value="batch_update">批量更新客户来源</option>
                                    <option value="batch_reverse">公户转私户</option>
                                </select>
                                <button class="btn btn-danger" style="vertical-align: 1px;">执行</button>
                                <!-- /.box-header -->
                                <div class="box-body">
                                    <table id="example2" class="table table-bordered table-hover">
                                        <thead>
                                        <tr>
                                            <th>
                                                <input type="checkbox" id="choose">
                                            </th>
                                            <th>序号</th>
                                            <th>qq</th>
                                            <th>姓名</th>
                                            <th>性别</th>
                                            <th>客户来源</th>
                                            <th>咨询课程</th>
                                            <th>跟进记录</th>
                                            <th>操作</th>
                                        </tr>
                                        </thead>
                                        <tbody>
                                        {% for customer in all_customers %}
                                            <tr>
                                                <td><input type="checkbox" name="selected_id" value="{{ customer.pk }}">
                                                </td>
                                                <td>{{ forloop.counter }}</td>
                                                <td>{{ customer.qq }}</td>
                                                <td>{{ customer.name }}</td>
                                                <td>{{ customer.get_sex_display }}</td>
                                                <td>{{ customer.get_source_display }}</td>
                                                <td>{{ customer.course }}</td>
                                                <td><a href="{% url 'singlerecord' customer.pk %}">跟进详情</a></td>
                                                <td><a href="{% url 'edit' customer.pk %}"
                                                       class="btn btn-warning btn-sm">编辑</a>
                                                    <a href="{% url 'delete' customer.pk %}"
                                                       class="btn btn-danger btn-sm">删除</a>
                                                </td>
                                            </tr>
                                        {% endfor %}
                                        </tbody>
                                    </table>
                                </div>
                            </form>
                        </div>
                    </div>
                    {{ ret_html|safe }}
                </div>
            </div>
        </div>
    </section>
{% endblock %}

{% block js %}
    <script>
        $('#choose').click(function () {
            var status = $(this).prop('checked');
            $('[name=selected_id]').prop('checked', status);
        })
    </script>

{% endblock %}

managerment_system/templates/edit.html
{% extends 'base.html' %}

{% block content %}

    <h3>这是编辑页面</h3>
    <div class="container-fluid">
        <div class="row">
            <div class="col-md-8 col-md-offset-2">
                <form action="" method="post" novalidate>
                    {% csrf_token %}
                    {% for field in form_obj %}
                        <div class="form-group">
                            <label for="{{ field.id_for_label }}">{{ field.label }}</label>
                            {{ field }}
                            <span class="text-danger">{{ field.errors.0 }}</span>
                        </div>
                    {% endfor %}

                    <input type="submit" class="btn btn-success pull-right" value="提交">
                </form>
            </div>
        </div>
    </div>

{% endblock %}

managerment_system/templates/editfollow.html
{% extends 'base.html' %}

{% block content %}

    <h3>这是编辑跟进记录的页面</h3>
    <div class="container-fluid">
        <div class="row">
            <div class="col-md-8 col-md-offset-2">
                <form action="" method="post" novalidate>
                    {% csrf_token %}
                    {% for field in form_obj %}
                        <div class="form-group">
                            <label for="{{ field.id_for_label }}">{{ field.label }}</label>
                            {{ field }}
                            <span class="text-danger">{{ field.errors.0 }}</span>
                        </div>
                    {% endfor %}
                    <input type="submit" class="btn btn-success pull-right" value="提交">
                </form>
            </div>
        </div>
    </div>

{% endblock %}

managerment_system/templates/followrecord.html
{% extends 'base.html' %}

{% block content %}
    <section class="content">
        <div class="row">
            <div class="col-xs-12">
                <div class="box">
                    <div class="box-header">
                        <div>
                            <h3 class="box-title">我的客户跟进记录</h3>
                        </div>
                        <div>
                            <br>
                            <form action="" method="get" class="pull-right" style="width: 400px;display: inline-block">
                                <select name="condition" id="" class="form-control"
                                        style="width: 110px;display: inline-block">
                                    <option value="customer__name__contains">客户名</option>
                                </select>
                                <input type="text" name="wd" class="form-control"
                                       style="width: 200px;display: inline-block">
                                <button class="btn btn-default">搜索</button>
                            </form>
                            <a href="{% url 'addfollow' %}" style="margin-left:10px;"
                               class="btn btn-primary pull-left">添加</a>
                            <form action="" method="post">
                                {% csrf_token %}
                                <select name="action" id="" class="form-control"
                                        style="width: 200px;display: inline-block;margin-left: 5px;">
                                    <option value="batch_delete">批量删除</option>
                                    <option value="batch_update">批量更新状态</option>
                                </select>
                                <button class="btn btn-danger" style="vertical-align: 1px;">执行</button>
                                <div class="box-body">
                                    <table class="table table-bordered table-hover">
                                        <thead>
                                        <tr>
                                            <th><input type="checkbox" id="choose"></th>
                                            <th>序号</th>
                                            <th>客户名</th>
                                            <th>跟进内容</th>
                                            <th>跟进状态</th>
                                            <th>跟进人</th>
                                            <th>跟进日期</th>
                                            <th>操作</th>
                                        </tr>
                                        </thead>
                                        <tbody>
                                        {% for followrecord in my_followrecord %}
                                            <tr>
                                                <td><input type="checkbox" name="selected_id"
                                                           value="{{ followrecord.pk }}"></td>
                                                <td>{{ forloop.counter }}</td>
                                                <td>{{ followrecord.customer }}</td>
                                                <td>{{ followrecord.note }}</td>
                                                <td>{{ followrecord.get_status_display }}</td>
                                                <td>{{ followrecord.consultant }}</td>
                                                <td>{{ followrecord.date|date:'Y-m-d' }}</td>
                                                <td><a href="{% url 'editfollow' followrecord.pk %}"
                                                       class="btn btn-warning btn-sm">编辑</a> <a
                                                        href="{% url 'delfollow' followrecord.pk %}"
                                                        class="btn btn-danger btn-sm">删除</a></td>
                                            </tr>
                                        {% endfor %}
                                        </tbody>
                                    </table>
                                </div>
                            </form>
                        </div>
                    </div>
                    {{ ret_html|safe }}
                </div>
            </div>
        </div>
    </section>

{% endblock %}

{% block js %}
    <script>
        $('#choose').click(function () {
            var status = $(this).prop('checked');
            $('[name=selected_id]').prop('checked',status);
        })
    </script>
{% endblock %}

managerment_system/templates/index.html
{% extends 'base.html' %}

managerment_system/templates/login.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>login</title>
    <link rel="stylesheet" href="{% static 'bootstrap-3.3.7-dist/css/bootstrap.min.css' %}">
</head>
<body>

<h1>管理系统的登录页面</h1>
<div class="container-fluid">
    <div class="row">
        <div class="col-md-6 col-md-offset-3">
            <form>
                {% csrf_token %}
                <div class="form-group">
                    <label for="username">用户名</label>
                    <input type="text" id="username" name="username" class="form-control">
                </div>
                <div class="form-group">
                    <label for="password">密码</label>
                    <input type="password" id="password" name="password" class="form-control">
                </div>
                <div class="row">
                    <div class="col-md-6">
                        <div class="form-group">
                            <label for="code">验证码</label>
                            <input type="text" id="code" name="code" class="form-control">
                        </div>
                    </div>
                    <div class="col-md-6">
                        <img src="{% url 'code' %}" alt="" id="code_img" style="margin-top: 24px;margin-left:48px;">
                    </div>
                </div>
                <span id="error" class="text-danger"></span>
                <input type="button" id="login" value="登录" class="btn btn-success pull-right">
            </form>
        </div>
    </div>
</div>

<script src="{% static 'jquery-3.4.1.js' %}"></script>
<script src="{% static 'bootstrap-3.3.7-dist/js/bootstrap.min.js' %}"></script>

<script>
    $('#login').click(function () {
       var username = $('#username').val();
       var password = $('#password').val();
       var code = $('#code').val();
       var csrf_token = $('[name=csrfmiddlewaretoken]').val();

        $.ajax({
            url:'{% url "login" %}',
            type:'post',
            data:{
                username:username,
                password:password,
                code:code,
                csrfmiddlewaretoken:csrf_token,
            },
            success:function (res) {
                if (res.code === 100){
                    var herf = location.search.slice(6);
                    if (herf){
                        location.href = herf;
                    }else{
                        location.href = '{% url "index" %}';
                    }
                }
                else{
                    $('#error').text(res.msg);
                }
            }
        })
    });

    $('#code_img').click(function () {
        $(this)[0].src += '?';
    })
</script>

</body>
</html>

managerment_system/templates/menu.html
{#{% for foo in menu_list %}#}
{#    <li class={{ foo.class }}><a href="{{ foo.url }}"><i class="fa fa-link"></i> <span>{{ foo.name }}</span></a></li>#}
{#{% endfor %}#}

{% for item in menu_dict.values %}
    <li class="treeview {{ item.class }}" >
        <a href=""><i class="fa fa-link"></i> <span>{{ item.name }}</span><span class="pull-right-container"></span><i
                class="fa fa-angle-left pull-right"></i></a>
        <ul class="treeview-menu" style="display: block">
            {% for foo in item.children %}
                <li class="{{ foo.class }}"><a  href="{{ foo.url }}">{{ foo.name }}</a></li>
            {% endfor %}
        </ul>
    </li>
{% endfor %}

managerment_system/templates/mycustomers.html
{% extends 'base.html' %}

{% block content %}

    <section class="content">
        <div class="row">
            <div class="col-xs-12">
                <div class="box">
                    <div class="box-header">
                        <div>
                            <h3 class="box-title">我的客户信息展示</h3>
                        </div>
                        <div>
                            <br>
                            <form action="" method="get" class="pull-right" style="width: 400px;display: inline-block">
                                <select name="condition" id="" class="form-control"
                                        style="width: 100px;display: inline-block">
                                    <option value="name__contains">姓名</option>
                                    <option value="qq__contains">QQ</option>
                                </select>
                                <input type="text" name="wd" class="form-control"
                                       style="width: 200px;display: inline-block">
                                <button class="btn btn-default">搜索</button>
                            </form>
                            <a href="{% url 'add' %}" style="margin-left:10px;"
                               class="btn btn-primary pull-left">添加</a>
                            <form action="{% url 'mycustomers' %}" method="post">
                                {% csrf_token %}
                                <select name="action" id="" class="form-control"
                                        style="width: 200px;display: inline-block;margin-left: 5px;">
                                    <option value="batch_delete">批量删除</option>
                                    <option value="batch_update">批量更新客户来源</option>
                                    <option value="batch_reverse">私户转公户</option>
                                </select>
                                <button class="btn btn-danger" style="vertical-align: 1px;">执行</button>

                                <!-- /.box-header -->
                                <div class="box-body">
                                    <table id="example2" class="table table-bordered table-hover">
                                        <thead>
                                        <tr>
                                            <th>
                                                <input type="checkbox" id="choose">
                                            </th>
                                            <th>序号</th>
                                            <th>qq</th>
                                            <th>姓名</th>
                                            <th>性别</th>
                                            <th>客户来源</th>
                                            <th>咨询课程</th>
                                            <th>操作</th>
                                        </tr>
                                        </thead>
                                        <tbody>
                                        {% for customer in my_customers %}
                                            <tr>
                                                <td><input type="checkbox" name="selected_id" value="{{ customer.pk }}">
                                                </td>
                                                <td>{{ forloop.counter }}</td>
                                                <td>{{ customer.qq }}</td>
                                                <td>{{ customer.name }}</td>
                                                <td>{{ customer.get_sex_display }}</td>
                                                <td>{{ customer.get_source_display }}</td>
                                                <td>{{ customer.course }}</td>
                                                <td><a href="{% url 'edit' customer.pk %}"
                                                       class="btn btn-warning btn-sm">编辑</a>
                                                    <a href="{% url 'delete' customer.pk %}"
                                                       class="btn btn-danger btn-sm">删除</a>
                                                </td>
                                            </tr>
                                        {% endfor %}
                                        </tbody>
                                    </table>
                                </div>
                            </form>
                        </div>
                    </div>
                    {{ ret_html|safe }}
                </div>
            </div>
        </div>
    </section>
{% endblock %}

{% block js %}
    <script>
        $('#choose').click(function () {
            var status = $(this).prop('checked');
            $('[name=selected_id]').prop('checked', status);
        })
    </script>

{% endblock %}

managerment_system/templates/regiest.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>regiest</title>
    <link rel="stylesheet" href="{% static 'bootstrap-3.3.7-dist/css/bootstrap.min.css' %}">
</head>
<body>

<h1>管理系统的注册页面</h1>
<div class="container-fluid">
    <div class="row">
        <div class="col-md-6 col-md-offset-3">
            <form action="{% url 'regiest' %}" method="post" novalidate>
                {% csrf_token %}
                {% for foo in form_obj %}
                    <div class="form-group">
                        <label for="{{ foo.id_for_label }}">{{ foo.label }}</label>
                        {{ foo }}
                        <span class="text-danger">{{ foo.errors.0 }}</span>
                    </div>
                {% endfor %}
                <input type="submit" class="btn btn-success pull-right" value="注册">
            </form>
        </div>
    </div>
</div>

<script src="{% static 'jquery-3.4.1.js' %}"></script>
<script src="{% static 'bootstrap-3.3.7-dist/js/bootstrap.min.js' %}"></script>

</body>
</html>